name: ğŸ“Š Coverage

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Trigger the workflow on push to the main
  push:

permissions:
  contents: write

jobs:
  coverage-report-pipeline:
    name: ğŸ” Report
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ  Checkout code
        uses: actions/checkout@v4

      - name: ğŸº Prepare - Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Backend Coverage
      - name: ğŸ’» Install Backend Dependencies
        run: npm ci
        working-directory: ./backend

      - name: ğŸ§ª Run Backend Tests and Generate Coverage
        run: npm run coverage
        working-directory: ./backend

      - name: ğŸ“‚ Upload Backend Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: backend/coverage/
          overwrite: true

      # UI Coverage
      - name: ğŸ’» Install UI Dependencies
        run: npm ci
        working-directory: ./ui

      - name: ğŸ§ª Run UI Tests and Generate Coverage
        run: npm run test -- --coverage
        working-directory: ./ui

      - name: ğŸ“‚ Upload UI Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: ui-coverage-report
          path: ui/coverage/
          overwrite: true

      # Upload to GitHub Pages
      - name: ğŸ“‚ Upload Backend Coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./backend/coverage
          destination_dir: coverage/backend

      - name: ğŸ“‚ Upload UI Coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui/coverage
          destination_dir: coverage/ui

      - name: ğŸ“‚ Upload README to GitHub Pages root
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: .
          # keep_files: true
          enable_jekyll: true
